runelite.title=Hazy
runelite.version=1.0.0
runelite.commit=local
runelite.dirty=false
runelite.config=https://static.runelite.net/config.json
runelite.discord.invite=https://discord.gg/none
runelite.osrs.twitter=https://twitter.com/OldSchoolRS
runelite.wiki.troubleshooting=https://github.com
runelite.wiki.building=https://github.com
runelite.dnschange=https://github.com
runelite.jav_config=http://oldschool.runescape.com/jav_config.ws
runelite.jav_config_backup=https://github.com
runelite.pluginhub.version=1.0.0
runelite.pluginhub.url=https://github.com
runelite.api.base=https://api.runelite.net
